export const NAVIGATE_ABOUTPAGE='NAVIGATE_ABOUTPAGE';
export const NAVIGATE_CONTACTPAGE='NAVIGATE_CONTACTPAGE';
export const NAVIGATE_HOMEPAGE='NAVIGATE_HOMEPAGE';
export const NAVIGATE_SCHOOL='NAVIGATE_SCHOOL';
export const OPEN_LOGINFORM='OPEN_LOGINFORM';
export const CLOSE_LOGINFORM='CLOSE_LOGINFORM';
export const OPEN_SIGNUPFORM='OPEN_SIGNUPFORM';
export const CLOSE_SIGNUPFORM='CLOSE_SIGNUPFORM';